name: Python CI

on: [push]

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Run lesson1
        run: python lesson1.py
      - name: Run lesson2
        run: python lesson2.py
      - name: Run lesson3
        run: python lesson3.py
      - name: Run lesson4
        run: python lesson4.py